export const DEMOGRAPHIC_LABELS = {
  PF1: "Sexo",
  PF2: "Idade",
  "PF2#1": "Faixa Etária",
  PF2_faixas: "Faixa de idade",
  PF3: "Escolaridade",
  PF4: "Trabalho remunerado",
  PF5: "Classificação do trabalho",
  PF6: "Vínculo formal de trabalho",
  PF7: "Possui CNPJ",
  PF8: "Situação de trabalho",
  PF9: "Procurou emprego",
  PF12: "Recebeu Auxílio (últimos 3 anos)",
  PF13: "Recebe Auxílio (atualmente)",
  "PF13.1": "Filhos de 0 a 6 anos",
  "PF13.2": "Filhos de 7 a 17 anos",
  PF14: "Renda mensal individual",
  PF15: "Renda familiar mensal",
  PF16: "Religião",
  PF17: "Raça/Cor",
  UF: "Estado",
}
